services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
      - $GATEWAY_SERVICE_PORT:$GATEWAY_SERVICE_PORT
      - $DB_SERVICE_PORT:$DB_SERVICE_PORT
      - $AUTH_SERVICE_PORT:$AUTH_SERVICE_PORT
      - $FUNCTIONS_SERVICE_PORT:$FUNCTIONS_SERVICE_PORT
      - $NOTIFICATION_SERVICE_PORT:$NOTIFICATION_SERVICE_PORT
      - $STORAGE_SERVICE_PORT:$STORAGE_SERVICE_PORT
    command: ["/bin/sh", "-c", "yarn dev"]
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/ignitocore/node_modules
      - /app/apps/ignitoDB/node_modules
      - /app/apps/frontend/node_modules
      - /app/packages/eslint-config-custom/node_modules
      - /app/packages/tsconfig/node_modules
      - /app/packages/ui/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0-alpine3.18
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - $PG_PORT:$PG_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DATABASE_NAME -U $DATABASE_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
